"""DB

Revision ID: 55a0a0861f2f
Revises: 
Create Date: 2024-10-10 00:16:17.319659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55a0a0861f2f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lessons',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('group', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('telegram_id')
    )
    op.create_table('week_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_code', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedule',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('number_of_lesson', sa.Integer(), nullable=False),
    sa.Column('audience', sa.String(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.Column('group', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedule_day'), 'schedule', ['day'], unique=False)
    op.create_index(op.f('ix_schedule_group'), 'schedule', ['group'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_schedule_group'), table_name='schedule')
    op.drop_index(op.f('ix_schedule_day'), table_name='schedule')
    op.drop_table('schedule')
    op.drop_table('week_type')
    op.drop_table('users')
    op.drop_table('lessons')
    op.drop_table('groups')
    # ### end Alembic commands ###
