services:
  bot:
    container_name: schedule_bot
    build:
      dockerfile: Dockerfile
      context: .
    command: python -m src.bot
    env_file:
      - .env
    depends_on:
      - postgres
      - redis

  postgres:
    container_name: schedule_bot_postgres
    image: postgres:17-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data"

  redis:
    container_name: schedule_bot_redis
    image: redis:latest
    restart: unless-stopped
    command:
      - redis-server

volumes:
  db_data: