name: "schedule-bot"

services:
  postgres:
    user: root
    image: postgres:16-alpine
    restart: "always"
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      POSTGRES_DB:
    volumes:
      - "./schedule-app_bot-data-postgres:/var/lib/postgresql/data"

  nats:
    image: nats:latest
    entrypoint: /nats-server
    command: "-c /config/server.conf"
    ports:
      - "4222:4222"
      - "8222:8222"
    volumes:
      - ./nats/data:/data
      - ./nats/config/server.conf:/config/server.conf

  redis:
    image: redis:latest
    command:
      - redis-server
    restart: on-failure
    volumes:
      - "./schedule-app_bot-data-redis:/var/lib/redis/data"