name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  testing:
    name: Testing schedule_bot_dialog
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: setup dependencies
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"

    - name: Install uv
      uses: astral-sh/setup-uv@v7

    - name: Install dependencies
      run: |
        uv pip install -e . --system ".[lint]"

    - name: Run ruff
      run: |
        ruff check
